packages:
  # all packages in direct subdirs of packages/
  - 'core/packages/*'
  - 'packages/testing-volto-searchkit-block'
  - 'packages/volto-bookmarks/packages/volto-bookmarks'
  - 'packages/volto-searchkit-block'
