# syntax=docker/dockerfile:1
# Dockerfile from cookiecutter-plone-starter
ARG PLONE_VERSION=6.0
FROM plone/server-builder:${PLONE_VERSION} as builder

WORKDIR /app

# # Add local code
# COPY . .


# Install local requirements
RUN <<EOT
    set -e
    bin/pip install collective.elastic.plone[redis,opensearch]>=2.0.1
EOT




FROM plone/server-prod-config:${PLONE_VERSION}

# Use /app as the workdir
WORKDIR /app

# Copy /app from builder
COPY --from=builder --chown=500:500 /app /app

# # Enable compilation of po files into mo files (This is added here for backward compatibility)

# ENV zope_i18n_compile_mo_files=true
# # https://github.com/pypa/pip/issues/12079
# ENV _PIP_USE_IMPORTLIB_METADATA=0

# Link /data (the exposed volume) into /app/var
RUN ln -s /data /app/var