version: "3"

services:
  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile.ci
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    # TODO Create content
    build:
      context: ../
      dockerfile: ./dockerfiles/backend/Dockerfile.acceptance
      args:
        PLONE_VERSION: ${PLONE_VERSION:-6.0}
    environment:
      ZSERVER_HOST: 0.0.0.0
      ZSERVER_PORT: 55001
      # plone.elastic 2.x
      INDEX_SERVER: opensearch:9200
      CELERY_BROKER: redis://redis:6379/0
      INDEX_LOGIN: admin
      INDEX_PASSWORD: admin
      INDEX_OPENSEARCH: 1
      INDEX_USE_SSL: 0
    ports:
      - 55001:55001
    depends_on:
      - ingest
      - redis
      - opensearch
    profiles:
      - dev
      - prod

  ingest:
    build:
      context: ../
      dockerfile: ./docker-opensearch/Dockerfile.ingest
    environment:
      MAPPINGS_FILE: "/configuration/mappings.json"
      ANALYSIS_FILE: "/configuration/analysis.json"
      PREPROCESSINGS_FILE: "/configuration/preprocessings.json"
      INDEX_SERVER: opensearch:9200
      INDEX_USE_SSL: 1
      INDEX_OPENSEARCH: 1
      INDEX_LOGIN: admin
      INDEX_PASSWORD: admin
      CELERY_BROKER: redis://redis:6379/0
      CELERY_CONCURRENCY: "-1"
      CELEREY_LOG_LEVEL: "-info"
      PLONE_SERVICE: http://backend-acceptance:55001
      PLONE_SITE_PREFIX_PATH: plone
      PLONE_USER: admin
      PLONE_PASSWORD: secret
    # volumes:
    #   - ingest-configuration:/configuration

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

  opensearch:
    build:
      context: ../
      dockerfile: ./docker-opensearch/Dockerfile.opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    profiles:
      - dev
      - prod
