version: "3"

services:
  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/frontend/Dockerfile.ci
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  addon-acceptance-multilingual:
    build:
      context: ../
      dockerfile: ./dockerfiles/frontend/Dockerfile.ci.multilingual
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance-multilingual:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance-multilingual
    profiles:
      - multilingual
  

  backend-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/backend/Dockerfile.acceptance
      args:
        PLONE_VERSION: ${PLONE_VERSION:-6.0}
    environment:
      ZSERVER_HOST: 0.0.0.0
      ZSERVER_PORT: 55001
      # plone.elastic 2.x
      INDEX_SERVER: ${INDEX_SERVER?unset}
      INDEX_OPENSEARCH: ${INDEX_OPENSEARCH?unset}
      INDEX_USE_SSL: ${INDEX_USE_SSL?unset}
      INDEX_LOGIN: ${INDEX_LOGIN?unset}
      INDEX_PASSWORD: ${INDEX_PASSWORD?unset}
      CELERY_BROKER: ${CELERY_BROKER?unset}
      CONFIGURE_PACKAGES: "plone.restapi,plone.volto,plone.volto.cors,collective.elastic.plone"
      # Run initialize of collective.elastic.plone to register ElasticSearchProxyIndex
      INSTALL_PRODUCTS: "collective.elastic.plone"
    ports:
      - 55001:55001
    depends_on:
      - ingest
      - redis
      - opensearch
    profiles:
      - dev
      - prod
  

  backend-acceptance-multilingual:
    build:
      context: ../
      dockerfile: ./dockerfiles/backend/Dockerfile.acceptance.multilingual
      args:
        PLONE_VERSION: ${PLONE_VERSION:-6.0}
    environment:
      ZSERVER_HOST: 0.0.0.0
      ZSERVER_PORT: 55001
      # plone.elastic 2.x
      INDEX_SERVER: ${INDEX_SERVER?unset}
      INDEX_OPENSEARCH: ${INDEX_OPENSEARCH?unset}
      INDEX_USE_SSL: ${INDEX_USE_SSL?unset}
      INDEX_LOGIN: ${INDEX_LOGIN?unset}
      INDEX_PASSWORD: ${INDEX_PASSWORD?unset}
      CELERY_BROKER: ${CELERY_BROKER?unset}
      CONFIGURE_PACKAGES: "plone.restapi,plone.volto,plone.volto.cors,collective.elastic.plone"
      # Run initialize of collective.elastic.plone to register ElasticSearchProxyIndex
      INSTALL_PRODUCTS: "collective.elastic.plone"
    ports:
      - 55001:55001
    depends_on:
      - ingest-multilingual
      - redis
      - opensearch
    profiles:
      - multilingual

  ingest:
    build:
      context: ../
      dockerfile: .//Dockerfile.ingest
    environment:
      MAPPINGS_FILE: "/configuration/mappings.json"
      ANALYSIS_FILE: "/configuration/analysis.json"
      PREPROCESSINGS_FILE: "/configuration/preprocessings.json"
      INDEX_SERVER: ${INDEX_SERVER?unset}
      INDEX_OPENSEARCH: ${INDEX_OPENSEARCH?unset}
      INDEX_USE_SSL: ${INDEX_USE_SSL?unset}
      INDEX_LOGIN: ${INDEX_LOGIN?unset}
      INDEX_PASSWORD: ${INDEX_PASSWORD?unset}
      CELERY_BROKER: ${CELERY_BROKER?unset}
      CELERY_CONCURRENCY: ${CELERY_CONCURRENCY:-1}
      CELEREY_LOG_LEVEL: ${CELERY_LOG_LEVEL:-info}
      PLONE_SERVICE: ${PLONE_SERVICE?unset}
      PLONE_SITE_PREFIX_PATH: ${PLONE_SITE_PREFIX_PATH?unset}
      PLONE_USER: ${PLONE_USER?unset}
      PLONE_PASSWORD: ${PLONE_PASSWORD?unset}

  ingest-multilingual:
    build:
      context: ../
      dockerfile: .//Dockerfile.ingest
    environment:
      # Different INDEX_NAME
      MAPPINGS_FILE: "/configuration/mappings.json"
      ANALYSIS_FILE: "/configuration/analysis.json"
      PREPROCESSINGS_FILE: "/configuration/preprocessings.json"
      INDEX_SERVER: ${INDEX_SERVER?unset}
      INDEX_NAME: multilingual
      INDEX_OPENSEARCH: ${INDEX_OPENSEARCH?unset}
      INDEX_USE_SSL: ${INDEX_USE_SSL?unset}
      INDEX_LOGIN: ${INDEX_LOGIN?unset}
      INDEX_PASSWORD: ${INDEX_PASSWORD?unset}
      CELERY_BROKER: ${CELERY_BROKER?unset}
      CELERY_CONCURRENCY: ${CELERY_CONCURRENCY:-1}
      CELEREY_LOG_LEVEL: ${CELERY_LOG_LEVEL:-info}
      PLONE_SERVICE: http://backend-acceptance-multilingual:55001
      PLONE_SITE_PREFIX_PATH: ${PLONE_SITE_PREFIX_PATH?unset}
      PLONE_USER: ${PLONE_USER?unset}
      PLONE_PASSWORD: ${PLONE_PASSWORD?unset}

  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379

  opensearch:
    build:
      context: ../
      dockerfile: .//Dockerfile.opensearch
    environment:
      - plugins.security.disabled=true
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx2g"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${INDEX_PASSWORD?unset}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
