version: "3"

services:
  addon-acceptance:
    build:
      context: ../
      dockerfile: ./dockerfiles/Dockerfile
      args:
        ADDON_NAME: "${ADDON_NAME}"
        ADDON_PATH: "${ADDON_PATH}"
        VOLTO_VERSION: ${VOLTO_VERSION:-17}
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend-acceptance:55001/plone
      RAZZLE_API_PATH: http://localhost:55001/plone
    ports:
      - 3000:3000
    depends_on:
      - backend-acceptance
    profiles:
      - prod

  backend-acceptance:
    image: plone/server-acceptance:${PLONE_VERSION:-6.0}
    volumes:
      - ./configuration/ploneconfiguration/:/app/ploneconfiguration/
    environment:
      # INSTALL_PRODUCTS: "collective.elastic.plone,collective.elastic.ingest"
      ADDONS: "collective.elastic.plone"
      SITE: "plone"
      # DEVELOP: "git+https://github.com/collective/collective.elastic.plone.git#egg=collective.elastic.plone"
      # New with plone.elastic 2.x
      INDEX_SERVER: "http://host.docker.internal:9200"
      CELERY_BROKER: "redis://host.docker.internal:6379"
    ports:
      - 55001:55001
    profiles:
      - dev
      - prod

  # opensearch-acceptance:
  #   # TODO Move to docker-opensearch/Dockerfile
  #   build:
  #     context: ../
  #     dockerfile: ./docker-opensearch/Dockerfile
  #   environment:
  #       # TODO ingest environment variables
  #       ANALYSIS_FILE: /app/ploneconfiguration/elasticsearch-analysis.json
  #       MAPPINGS_FILE: /app/ploneconfiguration/elasticsearch-mappings.json
  #       PREPROCESSINGS_FILE: /app/ploneconfiguration/elasticsearch-preprocessings.json
  #   profiles:
  #     - dev
  #     - prod
