# syntax=docker/dockerfile:1
# The language is set here:
# PROFILES …:monolingual
ARG SEED=1000
ARG PLONE_VERSION=6.0
FROM plone/plone-backend:${PLONE_VERSION}


LABEL maintainer="Plone Foundation <collective@plone.org>" \
    org.label-schema.name="searchkit-backend" \
    org.label-schema.description="searchkit backend image." \
    org.label-schema.vendor="Rohberg"

# Add local code
COPY backend .

# # Install local requirements and fix permissions
# RUN <<EOT
#     ./bin/pip install mxdev
#     mv requirements-docker.txt requirements.txt
#     ./bin/mxdev -c mx.ini
#     ./bin/pip install -r requirements-mxdev.txt
#     chown -R plone: /app
# EOT


# Install local requirements and fix permissions
RUN <<EOT
    set -e
    # remove potentially existing virtualenv from local build
    rm -rf .venv
    mv requirements-docker.txt requirements.txt
    ./bin/pip install -r requirements.txt
    chown -R plone: /app
EOT

# Move package include
RUN <<EOT
    mv collective.elastic.plone-configure.zcml etc/package-includes/collective.elastic.plone-configure.zcml
EOT

# Create a new site with content
RUN <<EOT
    SEED=${SEED}
    # export ADDONS="collective.elastic.plone[redis,opensearch] rohberg.voltosearchkitblocktestingprofiles"
    export PROFILES="collective.elastic.plone:default rohberg.voltosearchkitblocktestingprofiles:monolingual"
    export DEBUG_MODE=on
    export DELETE_EXISTING=true
    ./docker-entrypoint.sh create-site
EOT
