FROM opensearchproject/opensearch:latest

COPY docker-opensearch/opensearch-configuration/keywords.txt /usr/share/opensearch/config/keywords.txt
COPY docker-opensearch/opensearch-configuration/lexicon.txt /usr/share/opensearch/config/lexicon.txt
COPY docker-opensearch/opensearch-configuration/keywords_english.txt /usr/share/opensearch/config/keywords_english.txt
COPY docker-opensearch/opensearch-configuration/lexicon_english.txt /usr/share/opensearch/config/lexicon_english.txt

RUN /usr/share/opensearch/bin/opensearch-plugin install --batch ingest-attachment
