name: Unit Tests
on: [push]

env:
  ADDON_NAME: '@rohberg/volto-searchkit-block'
  ADDON_PATH: volto-searchkit-block
  VOLTO_VERSION: 18.0.0-alpha.35
  PLONE_VERSION: 6.0

  INDEX_SERVER: opensearch:9200
  INDEX_OPENSEARCH: 1
  INDEX_USE_SSL: 0
  INDEX_LOGIN: admin
  INDEX_PASSWORD: 'oxczBG).3xWyapLn'

  CELERY_BROKER: redis://redis:6379/0
  CELERY_LOG_LEVEL: info

  PLONE_SERVICE: http://backend-acceptance:55001
  PLONE_SITE_PREFIX_PATH: plone
  PLONE_USER: admin
  PLONE_PASSWORD: secret

  MAPPINGS_FILE: /configuration/mappings.json
  ANALYSIS_FILE: /configuration/analysis.json
  PREPROCESSINGS_FILE: /configuration/preprocessings.json

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Main checkout
        uses: actions/checkout@v4

      - name: Unit tests
        run: make test-ci
